meta_product_name: "Trad'Food,"
meta_title: "Trad'Food | Manger et cuisiner traditionnel à Bordeaux"
meta_description: "Découvrez ou redécouvrez avec Trad'Food les meilleurs plats traditionnels de Bordeaux. Alliez l'utile à l'agréable avec nos recettes et notre sélection de vins..."
meta_image: "meta_image.jpg"
twitter_account: "@tradfood"
